version: 2
updates:
- package-ecosystem: gomod
  directory: /
  target-branch: main
  schedule:
    interval: daily
- package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily