linters:
  enable:
  - asciicheck
  - bodyclose
  - depguard
  - dogsled
  - durationcheck
  - exhaustive
  - exportloopref
  - gci
  - gofmt
  - gofumpt
  - goimports
  - golint
  - gomnd
  - gosec
  - govet
  - importas
  - lll
  - megacheck
  - misspell
  - nakedret
  - nilerr
  - nolintlint
  - predeclared
  - stylecheck
  - unconvert
  - unparam
  - wastedassign
issues:
  exclude-rules:
  - linters:
    - gosec
    text:  "weak cryptographic primitive"
    path: "state/indexers/md5Indexer.*"
  - linters:
    - gosec
    text:  "weak random number generator"
    path: _test\.go
  - linters:
    - errcheck
    text:  "Error return value" # ignore err not checked in test files
    path: _test\.go
  - linters:
    - gosec
    text:  "Expect WriteFile permissions to be 0600 or less"
    path: file/codegen/main.go
