builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  - freebsd
  goarch:
  - amd64
  asmflags:
  - all=-trimpath={{.Env.GOPATH}}
  ldflags:
  - -s -w -X github.com/alpiquero/deck/cmd.VERSION={{ .Tag }} -X github.com/alpiquero/deck/cmd.COMMIT={{ .ShortCommit }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
nfpms:
-  name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Arch }}'
   homepage:  https://github.com/alpiquero/deck
   description: Declarative configuration for Kong
   maintainer: Ángel Luis Piquero <alpiquero87@gmail.com>
   license: Apache License v2.0
   formats:
   - deb
   - rpm