package convert

const (
	awsLambdaPluginName                   = "aws-lambda"
	httpLogPluginName                     = "http-log"
	prefunctionPluginName                 = "pre-function"
	postfunctionPluginName                = "post-function"
	rateLimitingAdvancedPluginName        = "rate-limiting-advanced"
	aiRateLimitingAdvancedPluginName      = "ai-rate-limiting-advanced"
	graphqlProxyCacheAdvancedPluginName   = "graphql-proxy-cache-advanced"
	graphqlRateLimitingAdvancedPluginName = "graphql-rate-limiting-advanced"
	proxyCacheAdvancedPluginName          = "proxy-cache-advanced"
	aiProxyPluginName                     = "ai-proxy"
	aiProxyAdvancedPluginName             = "ai-proxy-advanced"
	aiRagInjectorPluginName               = "ai-rag-injector"
	aiRequestTransformerPluginName        = "ai-request-transformer"
	aiResponseTransformerPluginName       = "ai-response-transformer"
	aiSemanticCachePluginName             = "ai-semantic-cache"
	aiSemanticPromptGuardPluginName       = "ai-semantic-prompt-guard"

	// Auth plugins affected by hide_credentials default change in 3.14
	keyAuthPluginName             = "key-auth"
	keyAuthEncPluginName          = "key-auth-enc"
	basicAuthPluginName           = "basic-auth"
	hmacAuthPluginName            = "hmac-auth"
	ldapAuthPluginName            = "ldap-auth"
	oauth2PluginName              = "oauth2"
	oauth2IntrospectionPluginName = "oauth2-introspection"
	vaultAuthPluginName           = "vault-auth"
	ldapAuthAdvancedPluginName    = "ldap-auth-advanced"

	// Plugins affected by ssl_verify default change in 3.14
	acePluginName                     = "ace"
	acmePluginName                    = "acme"
	aiAwsGuardrailPluginName          = "ai-aws-guardrail"
	aiAzureContentSafetyPluginName    = "ai-azure-content-safety"
	aiLlmAsJudgePluginName            = "ai-llm-as-judge"
	aiSemanticResponseGuardPluginName = "ai-semantic-response-guard"
	azureFunctionsPluginName          = "azure-functions"
	confluentPluginName               = "confluent"
	confluentConsumePluginName        = "confluent-consume"
	datakitPluginName                 = "datakit"
	forwardProxyPluginName            = "forward-proxy"
	headerCertAuthPluginName          = "header-cert-auth"
	jwtSignerPluginName               = "jwt-signer"
	kafkaConsumePluginName            = "kafka-consume"
	kafkaLogPluginName                = "kafka-log"
	kafkaUpstreamPluginName           = "kafka-upstream"
	mtlsAuthPluginName                = "mtls-auth"
	opaPluginName                     = "opa"
	openidConnectPluginName           = "openid-connect"
	rateLimitingPluginName            = "rate-limiting"
	requestCalloutPluginName          = "request-callout"
	responseRateLimitingPluginName    = "response-ratelimiting"
	samlPluginName                    = "saml"
	serviceProtectionPluginName       = "service-protection"
	tcpLogPluginName                  = "tcp-log"
	upstreamOauthPluginName           = "upstream-oauth"
)
