package stats

type OutputFormat string

const (
	TextFormat     OutputFormat = "txt"
	CSVFormat      OutputFormat = "csv"
	HTMLFormat     OutputFormat = "html"
	MarkdownFormat OutputFormat = "md"
	JsonFormat     OutputFormat = "json"
	YamlFormat     OutputFormat = "yaml"
)

var EnterprisePluginsMap = map[string]bool{
	"ai-azure-content-safety":        true,
	"ai-proxy-advanced":              true,
	"ai-rate-limiting-advanced":      true,
	"ai-semantic-cache":              true,
	"ai-semantic-prompt-guard":       true,
	"app-dynamics":                   true,
	"application-registration":       true,
	"canary":                         true,
	"confluent":                      true,
	"degraphql":                      true,
	"exit-transformer":               true,
	"forward-proxy":                  true,
	"graphql-proxy-cache-advanced":   true,
	"graphql-rate-limiting-advanced": true,
	"header-cert-auth":               true,
	"injection-protection":           true,
	"jwe-decrypt":                    true,
	"jq":                             true,
	"json-threat-protection":         true,
	"jwt-signer":                     true,
	"kafka-log":                      true,
	"kafka-upstream":                 true,
	"key-auth-enc":                   true,
	"ldap-auth-advanced":             true,
	"mocking":                        true,
	"mtls-auth":                      true,
	"oauth2-introspection":           true,
	"oas-validation":                 true,
	"opa":                            true,
	"openid-connect":                 true,
	"proxy-cache-advanced":           true,
	"rate-limiting-advanced":         true,
	"request-transformer-advanced":   true,
	"request-validator":              true,
	"response-transformer-advanced":  true,
	"route-by-header":                true,
	"route-transformer-advanced":     true,
	"saml":                           true,
	"service-protection":             true,
	"statsd-advanced":                true,
	"tls-handshake-modifier":         true,
	"tls-metadata-headers":           true,
	"upstream-oauth":                 true,
	"upstream-timeout":               true,
	"vault-auth":                     true,
	"websocket-size-limit":           true,
	"websocket-validator":            true,
	"xml-threat-protection":          true,
}

var OSSPluginsMap = map[string]bool{
	"ai-proxy":                true,
	"ai-prompt-decorator":     true,
	"ai-prompt-guard":         true,
	"ai-prompt-template":      true,
	"ai-request-transformer":  true,
	"ai-response-transformer": true,
	"basic-auth":              true,
	"hmac-auth":               true,
	"jwt":                     true,
	"key-auth":                true,
	"ldap-auth":               true,
	"oauth2":                  true,
	"session":                 true,
	"acme":                    true,
	"bot-detection":           true,
	"cors":                    true,
	"ip-restriction":          true,
	"acl":                     true,
	"proxy-cache":             true,
	"rate-limiting":           true,
	"redirect":                true,
	"request-size-limiting":   true,
	"request-termination":     true,
	"response-ratelimiting":   true,
	"standard-webhooks":       true,
	"aws-lambda":              true,
	"azure-functions":         true,
	"pre-function":            true,
	"post-function":           true,
	"datadog":                 true,
	"opentelemetry":           true,
	"prometheus":              true,
	"statsd":                  true,
	"zipkin":                  true,
	"correlation-id":          true,
	"request-transformer":     true,
	"response-transformer":    true,
	"grpc-web":                true,
	"grpc-gateway":            true,
	"file-log":                true,
	"http-log":                true,
	"loggly":                  true,
	"syslog":                  true,
	"tcp-log":                 true,
	"udp-log":                 true,
}