name: Benchmarks

on:
  pull_request: {}


permissions:
  contents: read
  pull-requests: write

jobs:
  benchmark:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    strategy:
      matrix:
        kong_image:
        - 'kong:3.9'
    env:
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_IMAGE: ${{ matrix.kong_image }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          path: current
      # - name: Checkout main branch
      #   uses: actions/checkout@v4
      #   with:
      #     path: main
      #     ref: main
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          path: base
          ref: ${{ github.base_ref }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: current/go.mod
      - name: Install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest
      - name: Setup Kong
        working-directory: current
        run: make setup-kong
      - name: Run benchmarks on current branch
        working-directory: current
        run: |
          make benchmark-save
          mv benchmark_results.txt ../benchmark_results_current.txt
      - name: Run benchmarks on base branch
        working-directory: base
        run: |
          make benchmark-save
          mv benchmark_results.txt ../benchmark_results_base.txt
      # - name: Run benchmarks on main branch
      #   working-directory: main
      #   run: |
      #     if grep -q "benchmark-save" Makefile; then
      #       make benchmark-save
      #       mv benchmark_results.txt ../benchmark_results_main.txt
      #     else
      #       echo "benchmark-save target not found in main branch, creating placeholder results"
      #       # Create a placeholder benchmark result
      #       echo "no benchmark data available in main branch" > ../benchmark_results_main.txt
      #     fi
      - name: Compare benchmark results
        run: |
          benchstat -confidence 0.6 benchmark_results_base.txt benchmark_results_current.txt | tee benchmark_comparison.txt
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const comparison = fs.readFileSync('benchmark_comparison.txt', 'utf8');
            
            const comment = `## Benchmark Comparison Results
            
            \`\`\`
            ${comparison}
            \`\`\`
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });