name: e2e Test

on: [push, pull_request]

jobs:
  e2e-tests:
    strategy:
      matrix:
        kong_image:
        - 'kong:2.7.0'
    env:
      KONG_ANONYMOUS_REPORTS: "off"
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Setup Kong
        run: make setup-kong
      - name: Build
        run: make build
      - name: Run e2e tests
        run: make test.e2e