name: Enterprise Integration Test

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  integration:
    # Skip if the PR has the 'skip-ee' label
    if: ${{ github.event_name == 'push' || !contains(github.event.pull_request.labels.*.name, 'skip-ee') }}
    timeout-minutes: ${{ fromJSON(vars.DECK_WORKFLOW_GW_TIMEOUT || '10') }}
    strategy:
      matrix:
        kong_image:
        - 'kong/kong-gateway:2.8'
        - 'kong/kong-gateway:3.4'
        - 'kong/kong-gateway:3.5'
        - 'kong/kong-gateway:3.6'
        - 'kong/kong-gateway:3.7'
        - 'kong/kong-gateway:3.8'
        - 'kong/kong-gateway:3.9'
        - 'kong/kong-gateway:3.10'
        - 'kong/kong-gateway:3.11'
        - 'kong/kong-gateway:3.12'
        - 'kong/kong-gateway:3.13'
        - 'kong/kong-gateway:3.14'
        - 'kong/kong-gateway-dev:latest'
        router_flavor:
          - 'traditional_compatible'
          - 'expressions'
    env:
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_IMAGE: ${{ matrix.kong_image }}
      KONG_ROUTER_FLAVOR: ${{ matrix.router_flavor }}

    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: ${{secrets.DOCKER_ORG_NAME}}
          password: ${{secrets.DOCKER_ORG_TOKEN}}
      - uses: Kong/kong-license@master
        id: license
        with:
          op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Setup Kong
        env:
          KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
        run: make setup-kong-ee
      - name: Run integration tests
        env:
          KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
        run: make test-integration
        continue-on-error: ${{ matrix.kong_image == 'kong/kong-gateway-dev:latest' }}
