name: AI Gateway Integration Test

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  integration-ai-gateway:
    # Skip if the PR has the 'skip-ee' label
    if: ${{ github.event_name == 'push' || !contains(github.event.pull_request.labels.*.name, 'skip-ee') }}
    timeout-minutes: ${{ fromJSON(vars.DECK_WORKFLOW_GW_TIMEOUT || '10') }}
    strategy:
      matrix:
        kong_image:
        - kong/kong-ai-gateway-dev:2.0.1-rc.2
    env:
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_IMAGE: ${{ matrix.kong_image }}

    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: ${{secrets.DOCKER_ORG_NAME}}
          password: ${{secrets.DOCKER_ORG_TOKEN}}
      - uses: Kong/kong-license@master
        id: license
        with:
          op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Setup Kong
        env:
          KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
        run: make setup-kong-ee
      - name: Run AI Gateway integration tests
        env:
          KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
        run: make test-integration
