name: Enterprise Integration Test

on:
  push:
    branches:
    - main
  pull_request: {}

jobs:
  integration:
    strategy:
      matrix:
        kong_image:
        - 'kong/kong-gateway:1.5.0.11'
        - 'kong/kong-gateway:2.1.4.6'
        - 'kong/kong-gateway:2.2.1.3'
        - 'kong/kong-gateway:2.3.3.4'
        - 'kong/kong-gateway:2.4.1.3'
        - 'kong/kong-gateway:2.5.1.2'
        - 'kong/kong-gateway:2.6.0.2'
        - 'kong/kong-gateway:2.7'
        - 'kong/kong-gateway:2.8'
        - 'kong/kong-gateway:3.0'
        - 'kong/kong-gateway:3.1'
        - 'kong/kong-gateway:3.2'
        - 'kong/kong-gateway:3.3'
        - 'kong/kong-gateway-dev:latest'
    env:
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_IMAGE: ${{ matrix.kong_image }}
      KONG_LICENSE_DATA: ${{ secrets.KONG_LICENSE_DATA }}

    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_PULL_USERNAME}}
          password: ${{secrets.DOCKERHUB_PULL_TOKEN}}
      - name: Setup Kong
        run: make setup-kong-ee
      - name: Run integration tests
        run: make test-integration
