name: Enterprise Integration Test

on: [push, pull_request]

jobs:
  runnable:
    runs-on: ubuntu-latest
    environment: "Configure ci"
    outputs:
      runnable: ${{ steps.check.outputs.result }}
    steps:
    - name: Check secret availability
      id: check
      run: echo ::set-output name=result::${{ secrets.GHA_DOCKERHUB_PULL_USER != ''}}

  integration:
    needs: runnable
    if: "needs.runnable.outputs.runnable == 'true'"
    env:
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_IMAGE: 'kong/kong-gateway-internal:master-nightly-alpine'
      KONG_LICENSE_DATA: ${{ secrets.KONG_LICENSE_DATA }}

    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.18'
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.GHA_DOCKERHUB_PULL_USER}}
          password: ${{secrets.GHA_KONG_ORG_DOCKERHUB_PUBLIC_TOKEN}}
      - name: Setup Kong
        run: make setup-kong-ee
      - name: Run integration tests
        run: make test-integration
