name: Enterprise Integration Test

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
  pull_request: {}

jobs:
  integration:
    strategy:
      matrix:
        kong_image:
        - 'kong/kong-gateway:1.5.0.11'
        - 'kong/kong-gateway:2.1.4.6'
        - 'kong/kong-gateway:2.2.1.3'
        - 'kong/kong-gateway:2.3.3.4'
        - 'kong/kong-gateway:2.4.1.3'
        - 'kong/kong-gateway:2.5.1.2'
        - 'kong/kong-gateway:2.6.0.2'
        - 'kong/kong-gateway:2.7'
        - 'kong/kong-gateway:2.8'
        - 'kong/kong-gateway:3.0'
        - 'kong/kong-gateway:3.1'
        - 'kong/kong-gateway:3.2'
        - 'kong/kong-gateway:3.3'
        - 'kong/kong-gateway-dev:latest'
    env:
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_IMAGE: ${{ matrix.kong_image }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_PULL_USERNAME}}
          password: ${{secrets.DOCKERHUB_PULL_TOKEN}}
      - uses: Kong/kong-license@master
        id: license
        with:
          password: ${{ secrets.PULP_PASSWORD }}
      - name: Setup Kong
        env:
          KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
        run: make setup-kong-ee
      - name: Run integration tests
        env:
          KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
        run: make test-integration
