name: Validate Kong Gateway Release
concurrency:
  group: ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      kong_image:
        description: 'Kong Gateway Docker Image'
        required: true
        default: 'kong/kong-gateway-dev:latest'
      branch:
        description: 'decK Branch'
        required: true
        default: 'main'
jobs:
  integration:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    name: "${{ inputs.kong_image }} against ${{ inputs.branch }}"
    env:
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_IMAGE: ${{ inputs.kong_image }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      - name: Execution Information
        run: |
          echo "Kong Gateway Image = ${{ inputs.kong_image }}"
          echo "decK Branch = ${{ inputs.branch }}"
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          ref: ${{ inputs.branch }}
      - name: Setup go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: go.mod
      - uses: Kong/kong-license@master
        id: license
        with:
          op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Setup Kong
        env:
          KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
        run: make setup-kong-ee
      - name: Run integration tests
        env:
          KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
        run: make test-integration
